apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-unshorten
  labels:
    app: unshorten-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unshorten-api
  template:
    metadata:
      labels:
        app: unshorten-api
    spec:
      securityContext:
        # I don't always use k8s..but when I do I run as root
        runAsUser: 0
      containers:
      - name: unshorten-api-container
        image: "jmbmxer/link-unshorten:0.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP