apiVersion: apps/v1beta1
# StatefulSets are intended to be used with stateful applications and distributed systems.
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: vault
          image: vault:0.9.5
          args:
            - "server"
            - "-dev"
            - "-log-level=debug"
            - "-dev-root-token-id=not-intended-for-production-deployments"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
