kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: link-unshorten-clusterrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restrict-root
  verbs:
  - use
