# Bind the ClusterRole to the desired set of service accounts.
# Policies should typically be bound to service accounts in a namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: link-unshorten-rolebinding
  namespace: lab006
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: link-unshorten-clusterrole
subjects:
# All service accounts in the default namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
