apiVersion: v1
kind: Service
metadata:
 name: link-unshorten-service-non-root
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
 selector:
   app: unshorten-api
