apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: manicode/jenkins-dind
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/jenkins_home
          name: jenkins-home
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-home
        emptyDir: {}
